### ISSUE TITLE
Trello YML configuration file is in an outdate format

### ISSUE THREAD

**Issue by rwchan13** [DataKind-SG/test-driven-data-cleaning#2]
Should be

trello:
  api: <API KEY>
  token: <TOKEN>

**Comment by oliverxchen** [comment]
Not sure what you mean... Trello no longer needs `api_key` and `api_secret`? Or do you mean the indenting?

If you mean the indenting, I have `trello` as a top level key to allow future integrations (the file is badly named... it should be `.tddc_config.yml` instead of `.trello_config.yml`). So in future it might be:

```
trello:
    api_key: xxxxxxxxx
    api_secret: yyyyyyyy
    token: zzzzzzz
asana:
    api_key: aaaaaaaa
    api_secret: bbbbbbb
    token: ccccccc
pivotal_tracker:
    api_key: dddddd
    api_secret: eeeeeeeee
    token: ffffffff
```
